-- Development-only example for mapping an Auth user to a profile.
-- Never commit a real email address or auth UUID here.
-- Replace both placeholders in a private SQL editor session:

-- INSERT INTO public.profiles (auth_id, name, email, role)
-- VALUES (
--   '<AUTH_USER_UUID>',
--   'Authorised Staff Member',
--   '<STAFF_EMAIL>',
--   'admin'
-- )
-- ON CONFLICT (email) DO UPDATE
-- SET auth_id = EXCLUDED.auth_id,
--     name = EXCLUDED.name,
--     role = EXCLUDED.role;
